version: '3.8'

services:

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data-cards:/data/db
      - ./DokkanRest/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 
    networks:
      - soap-network

  rest-api:
    build:
      context: ./DokkanRest
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - soap-network
      
  soap-api:
    build:
      context: ./DokkanSoap
    ports:
      - "5000:5000" 
    restart: always
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: users
    depends_on:
      - mysqldb
    networks:
      - soap-network

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./DokkanSoap/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - soap-network

  mongo-seed:
    image: mongo:latest
    depends_on:
      - db
    volumes:
      - ./DokkanRest/pettans.json:/pettans.json
    entrypoint: >
      bash -c "mongoimport --host db --db test --collection Pettan --authenticationDatabase admin --username root --password example --file /pettans.json --jsonArray"
    networks:
      - soap-network

volumes:
  mongo-data-cards:
  mysql-data:

networks:
  soap-network:
    driver: bridge
