version: '3.8'

services:
  web:
    image: dokkan-soap-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=users;User=root;Password=admin;Port=3306;
    networks:
      - soap-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: your-password
    ports:
      - "3306:3306"
    networks:
      - soap-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  soap-network:
    driver: bridge

volumes:
  mysql-data:
