version: '3.8'

services:
  soap-api:
    build:
      context: .
    ports:
      - "5000:5000" 
    restart: always
    environment:
      FLASK_ENV: development 
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: users
    depends_on:
      - mysqldb
    networks:
      - soap-network

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - soap-network

volumes:
  mysql-data:

networks:
  soap-network:
    driver: bridge