version: '3.8'
services:
    #Servicios para el uso de la DokkanRest
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017  
    volumes:
      - mongo-data-pettan:/data/db
      - ./DokkanRest/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  # Servicio de la API REST (DokkanApi)
  rest-api:
    build:
      context: ./DokkanRest
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  # Servicio de la API SOAP (Usuarios)
  soap-api:
    build:
      context: ./DokkanSoapApi
    ports:
      - "8085:8085" 
    restart: always
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: users
    depends_on:
      - mysqldb
    networks:
      - soap-network

  # Servicio de MySQL para la API SOAP
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./DokkanSoap/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - soap-network
  
 # app:
  #  build: .
   # restart: always
    #ports:
     # - '3000:3000'
    #depends_on:
     # - db
     # - redis

  mongo-seed:
    image: mongo:latest
    depends_on:
      - db
    volumes:
      - ./pettans.json:/pettans.json
    entrypoint: >
          bash -c "mongoimport --host db --db test --collection Pettan --authenticationDatabase admin --username root --password example --file /pettans.json --jsonArray"
volumes:
  mongo-data-pettan:
  mysql-data:

networks:
  soap-network:
    driver: bridge
