version: '3.8'
services:
    #Servicios para el uso de la DokkanRest
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017  
    volumes:
      - mongo-data-pettan:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 


  # Servicio de la API REST (DokkanApi)
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db

  mongo-seed:
    image: mongo:latest
    depends_on:
      - db
    volumes:
      - ./pettans.json:/pettans.json
    entrypoint: >
          bash -c "mongoimport --host db --db test --collection Pettan --authenticationDatabase admin --username root --password example --file /pettans.json --jsonArray"
volumes:
  mongo-data-pettan:

