apiVersion: v1
kind: Service
metadata:
  name: dokkan-soap-api-svc
  namespace: agv-api
spec:
  selector:
    app: dokkan-soap-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP


#export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 -d)

#